image: mcr.microsoft.com/dotnet/sdk:9.0

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:9.0-windowsservercore-ltsc2025
  tags: [windows]
  before_script:
    - dotnet --version
  script:
    - dotnet build VolcanicTransport

test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  image: mcr.microsoft.com/dotnet/sdk:9.0-windowsservercore-ltsc2025
  tags: [windows]
  before_script:    
    # Restore NuGet packages to the local .nuget folder (inside the project directory).
    - dotnet restore VolcanicTransport/VolcanicTransport-Tests --packages .nuget

  script:
    - > 
      dotnet test VolcanicTransport/VolcanicTransport-Tests --no-restore
      --logger:"junit;MethodFormat=Class;FailureBodyFormat=Verbose"

    

  artifacts:
    paths:
      - ./*
    reports:
      junit:
        - ./TestResults/TestResults.xml

